In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
dataset = pd.read_csv('data-pajak-parkir-di-dki-jakarta-bulan-desember-2020.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [10]:
print(x)

[['Jakarta Barat' 31 12 2020 3970874005.0]
 ['Jakarta Pusat' 31 12 2020 nan]
 ['Jakarta Selatan' 31 12 2020 10510131146.0]
 ['Jakarta Timur' 31 12 2020 nan]
 ['Jakarta Utara' 31 12 2020 3464173701.0]]


In [11]:
print(y)

['Pajak Parkir' 'Pajak Parkir' 'Pajak Parkir' 'Pajak Parkir'
 'Pajak Parkir']


In [14]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:5])
x[:, 1:5] = imputer.transform(x[:, 1:5])

In [15]:
print(x)

[['Jakarta Barat' 31.0 12.0 2020.0 3970874005.0]
 ['Jakarta Pusat' 31.0 12.0 2020.0 5981726284.0]
 ['Jakarta Selatan' 31.0 12.0 2020.0 10510131146.0]
 ['Jakarta Timur' 31.0 12.0 2020.0 5981726284.0]
 ['Jakarta Utara' 31.0 12.0 2020.0 3464173701.0]]


In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [17]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 31.0 12.0 2020.0 3970874005.0]
 [0.0 1.0 0.0 0.0 0.0 31.0 12.0 2020.0 5981726284.0]
 [0.0 0.0 1.0 0.0 0.0 31.0 12.0 2020.0 10510131146.0]
 [0.0 0.0 0.0 1.0 0.0 31.0 12.0 2020.0 5981726284.0]
 [0.0 0.0 0.0 0.0 1.0 31.0 12.0 2020.0 3464173701.0]]


In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [19]:
print(y)

[0 0 0 0 0]


In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 1)


In [26]:
print(x_train)

[[0.0 1.0 0.0 0.0 0.0 31.0 12.0 2020.0 5981726284.0]
 [0.0 0.0 0.0 0.0 1.0 31.0 12.0 2020.0 3464173701.0]
 [1.0 0.0 0.0 0.0 0.0 31.0 12.0 2020.0 3970874005.0]
 [0.0 0.0 0.0 1.0 0.0 31.0 12.0 2020.0 5981726284.0]]


In [27]:
print(x_test)

[[0.0 0.0 1.0 0.0 0.0 31.0 12.0 2020.0 10510131146.0]]


In [28]:
print(y_train)

[0 0 0 0]


In [29]:
print(y_test)

[0]


In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:] = sc.transform(x_test[:, 4:])

In [33]:
print(x_train)

[[0.0 1.0 0.0 0.0 -0.5773502691896257 0.0 0.0 0.0 0.9877101159670835]
 [0.0 0.0 0.0 0.0 1.7320508075688774 0.0 0.0 0.0 -1.2087473382455522]
 [1.0 0.0 0.0 0.0 -0.5773502691896257 0.0 0.0 0.0 -0.7666728936886147]
 [0.0 0.0 0.0 1.0 -0.5773502691896257 0.0 0.0 0.0 0.9877101159670835]]


In [34]:
print(x_test)

[[0.0 0.0 1.0 0.0 5.551115123125783e-17 31.0 12.0 2020.0 10510131146.0]]
